# Generated by Django 5.0.8 on 2024-08-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0002_rename_sale_date_sale_date_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.CharField(default='No description available', max_length=500),
        ),
    ]
